---
title: "Quick plot of vessel GPX data"
author: "Kevin L. Stierhoff"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse, sf, here, mapview, tmaptools)
pacman::p_load_gh("SWFSC/atm")
pacman::p_load_gh("SWFSC/surveyR")

# global knitr chunk options
knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, message = FALSE, 
  fig.align = "center", dev = "png", dev.args = list(type = "cairo"), dpi = 150
)
knitr::opts_chunk$set(cache = FALSE)
```

```{r project-info, include=FALSE}
# Get project name from directory
prj.name <- last(unlist(str_split(here(),"/")))

# Get all settings files
settings.files <- dir(here("Doc/settings"))

# Source survey settings file
prj.settings <- settings.files[str_detect(settings.files, paste0("settings_", prj.name, ".R"))]
source(here("Doc/settings", prj.settings))
```

```{r process-files, out.width="100%"}
# Survey type (Core or Nearshore)
tx.types <- c("Nearshore") # c("Compulsory","Adaptive")
# Down-sample points?
downsample.points <- TRUE
# Buffer distance (nmi) for retaining nav points
buffer.dist <- 0.2

# GPX file name
ctd.file <- here::here("Data/Nav", "lm_ctd.gpx")
nav.file <- here::here("Data/Nav", "lm_nav.gpx")
waypoint.file <- here("Data/Nav", wpt.filename)

# Extract route
nav.gpx <- tmaptools::read_GPX(nav.file)

if (exists("ctd.file")) {
  ctds <- tmaptools::read_GPX(ctd.file)$waypoints %>% 
    atm::project_sf(crs = 4326) %>% 
    select(lon = X, lat = Y, name, time) %>% 
    arrange(time) %>% 
    st_as_sf(coords = c("lon","lat"), crs = 4326)  
}

# Convert to points
nav.points <- nav.gpx$track_points %>% 
  atm::project_sf(crs = 4326) %>% 
  select(time, long = X, lat = Y) %>% 
  arrange(time) %>% 
  st_as_sf(coords = c("long","lat"), crs = 4326) %>% 
  mutate(date = date(time),
         hour = hour(time),
         minute = minute(time)) 

if (downsample.points) {
  nav.points <- nav.points %>% 
    # Downsample by minute
    group_by(date, hour, minute) %>% 
    slice(1) 
}

nav.path <- nav.points %>% 
  ungroup() %>% 
  summarise(do_union = F) %>% 
  st_cast("LINESTRING")

# Read transect waypoints
wpts <- read_csv(waypoint.file)

# Convert planned transects to sf; CRS = crs.geog
wpts.sf <- wpts %>% 
  st_as_sf(coords = c("Longitude","Latitude"), crs = 4326) %>% 
  mutate(
    label = paste("Transect", Transect),
    popup = paste('<b>Transect:</b>', Transect, Type)
  )

transects.sf <- wpts.sf %>% 
  group_by(Type, Transect, Region) %>% 
  summarise(do_union = FALSE) %>% 
  st_cast("LINESTRING") %>% 
  ungroup() %>% 
  mutate(
    distance = round(as.numeric(st_length(.))/1852,1),
    label    = paste("Transect", Transect),
    popup    = paste('<b>Transect:</b>', Transect, Type, '<br/>',
                     'Distance:', distance, 'nmi<br/>')
  )

# Filter transects by type
tx.buffer <- transects.sf %>% 
  filter(Type %in% tx.types) %>% 
  st_buffer(dist = buffer.dist/60,endCapStyle = "FLAT")

# Filter nav that intersects planned transects
nav.tx <- nav.points %>% 
  st_intersection(tx.buffer)

# mapview(nav.path) + mapview(tx.buffer) + mapview(nav.tx, zcol = "Transect")
```

## Interactive map

An interactive map showing the locations of planned transects, the vessel path, vessel locations that fall within a **`r buffer.dist`** nmi buffer around each planned transect.

```{r interactive-map}
# Plot map
i.map <- mapview(filter(tx.buffer, Transect %in% unique(nav.tx$Transect))) + 
  mapview(filter(transects.sf, 
                 Type %in% tx.types,
                 Transect %in% unique(nav.tx$Transect)), 
          zcol = "Type") + 
  mapview(nav.path, color = "black") + 
  mapview(nav.tx) 

if (exists("ctds")) {
  i.map <- i.map +
  mapview(ctds, col.regions = "white", color = "red")
}

# Display map
i.map
```

## Output table

A table showing the start and end time of each transect and the nearest CTD cast, which is useful for selecting the appropriate ECS file for Echoview processing.

```{r tx-summary-table}
nav.summ <- nav.tx %>% 
  group_by(Transect) %>% 
  summarise(start = min(time),
            end = max(time)) %>% 
  st_set_geometry(NULL)

# Match transect to nearest CTD cast
transects.sf$ctd <- ctds$name[st_nearest_feature(transects.sf, ctds)]

nav.ctd <- transects.sf %>% 
  filter(Transect %in% unique(nav.tx$Transect),
                 Type %in% tx.types) %>% 
  select(Transect, ctd) %>% 
  st_set_geometry(NULL)

nav.summ <- left_join(nav.summ, nav.ctd) %>% 
  select(Transect, ctd, start, end)

write_csv(nav.summ, here("Output/plotVessel_GPX.csv"))

DT::datatable(nav.summ)
```



